### ISSUE TITLE
DiffEqBase is not "lightweight"

### ISSUE THREAD

**Issue by mauro3** [SciML/DiffEqBase.jl#618]
The "About"  says that DiffEqBase is lightweight, but in IMO it's not:
- 48 total dependencies
- precompile time >1min (on  Julia 1.5 and 1.6)
- subsequent load time 10s (1.5) and 3s (1.6)
  (on my fast laptop)

Not sure what to do here, nor do I expect any solution (nor could I provide one: so feel free to close).   However I thought to put it out there as it would be nice if DiffEqBase was so lightweight that including it as a dep would be a decision not requiring any consideration.

**Comment by ChrisRackauckas** [comment]
It has definitely grown over time. The problem is that it now serves two purposes. It now gives the interface and the standard implementations for many parts of the interface. For example, it makes sense to have the interface for all of the callbacks be together:

https://github.com/SciML/DiffEqBase.jl/blob/master/src/callbacks.jl#L1-L379

but then a lot of the solvers make use of the common callback implementation:

https://github.com/SciML/DiffEqBase.jl/blob/master/src/callbacks.jl#L381-L898

That implementation is what introduces the dependencies for the nonlinear solvers.

Then there's a linear and nonlinear common interface for choosing how to overload portions of the DifferentialEquation solver. But that's used everywhere, so it wouldn't make sense to put those helper functions in OrdinaryDiffEq, so pre-built linear solver helper functions live in DiffEqBase:

https://github.com/SciML/DiffEqBase.jl/blob/master/src/linear_nonlinear.jl#L1-L241

and that's where the IterativeSolvers.jl dependency comes in. 

At the same time, SciML has moved beyond DiffEq.  https://github.com/SciML/DiffEqBase.jl/blob/master/src/problems/basic_problems.jl is a clear example of this, where it all exists for things going on in ModelingToolkit, NeuralPDE, DiffEqOperators, etc. So there's `NonlinearProblem`, `QuadratureProblem`, etc. with common interfaces around those, instantiated by Quadrature.jl, GalacticOptim.jl, etc. 

What this is telling me is that we need to split the interface portion from the `*DiffEq` common implementation portion. The definition of the Problem and Solution objects needs to be a SciMLInterface.jl, and DiffEqBase.jl needs to be a package specifically for the shared functionality of the differential equation solvers.

I think I've mentioned this problem to @kanav99 before, but haven't moved too much on it yet.

**Comment by ChrisRackauckas** [comment]
Solved. Depend on SciMLBase for the truly lightweight one.

**Comment by ChrisRackauckas** [comment]
Downstream has all been notified:

https://github.com/PSORLab/DynamicBoundsBase.jl/issues/4
https://github.com/PSORLab/DynamicBoundspODEsDiscrete.jl/issues/7
https://github.com/PSORLab/DynamicBoundspODEsIneq.jl/issues/5
https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/129
https://github.com/briochemc/F1Method.jl/issues/13
https://github.com/byuflowlab/GXBeam.jl/issues/48
https://github.com/PIK-ICoNe/NetworkDynamics.jl/issues/109
https://github.com/USCqserver/OpenQuantumTools.jl/issues/85
https://github.com/dpad/OrbitalTrajectories.jl/issues/76
https://github.com/NREL-SIIP/PowerSimulationsDynamics.jl/issues/168
https://github.com/arnauqb/Qwind.jl/issues/18
https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/issues/180
https://github.com/JuliaRobotics/RigidBodySim.jl/issues/130
https://github.com/chenwilliam77/RiskAdjustedLinearizations.jl/issues/35
https://github.com/virgile-baudrot/TKTDsimulations.jl/issues/10
https://github.com/trixi-framework/Trixi.jl/issues/1006
https://github.com/CliMA/ClimaCore.jl/issues/331
https://github.com/Chemellia/ChemistryFeaturization.jl/issues/130
https://github.com/JuliaDynamics/ChaosTools.jl/issues/231
https://github.com/rveltz/BifurcationKit.jl/issues/49
https://github.com/JuliaOcean/AIBECS.jl/issues/88
https://github.com/DecisionMakingAI/BenchmarkEnvironments.jl/issues/15
https://github.com/ranocha/SummationByPartsOperators.jl/issues/115

**Comment by mauro3** [comment]
And the related discourse post: https://discourse.julialang.org/t/psa-the-right-dependency-to-reduce-from-differentialequations-jl/72757/2

Thanks Chris!
