### ISSUE TITLE
Release v6.116.0 breaks Sundials v4.11.4

### ISSUE THREAD

**Issue by ufechner7** [SciML/DiffEqBase.jl#880]
Since release 6.116.0 of DiffEqBase Sundials 4.11.4 is broken. Pre-compilation fails with 
```
  UndefVarError: AbstractDiffEqLinearOperator not defined
```
I cannot use a newer version of Sundials due to https://github.com/SciML/Sundials.jl/issues/392 .

Workaround:
Add an explicit dependency of DiffEqBase to my project with the compat entry:
```
DiffEqBase = "<6.116.0"
```
I don't think that this workaround is a good solution.

**Comment by ChrisRackauckas** [comment]
Try https://github.com/SciML/DiffEqBase.jl/pull/882

Though I highly recommend updating your code to something that is expected to work. Using MArrays with Sundials is not something that is expected to be fixed "soon". When it is fixed, it'll just be inefficient of course by design, it would just add reinterprets automatically. But if you add the reinterprets on your end then it should be the same thing.

**Comment by ufechner7** [comment]
Thanks!
