### ISSUE TITLE
Nine broken tests in DiffEqBase.jl

### ISSUE THREAD

**Issue by iajzenszmi** [SciML/DiffEqBase.jl#896]
Test Summary:              | Pass  Broken  Total   Time
ForwardDiff Dual Detection |  325       9    334  59.1s
 59.082542 seconds (65.70 M allocations: 3.777 GiB, 5.45% gc time, 66.07% compilation time: 30% of which was recompilation)
Test Summary:    | Pass  Total  Time
ODE default norm |   26     26  2.2s
  2.185851 seconds (2.10 M allocations: 116.773 MiB, 2.91% gc time, 97.10% compilation time)
Test Summary:              | Pass  Total  Time
ODE default unstable check |   18     18  0.8s
  0.848425 seconds (730.88 k allocations: 39.698 MiB, 94.90% compilation time)
118.652973 seconds (128.04 M allocations: 7.277 GiB, 5.18% gc time, 73.74% compilation time: 17% of which was recompilation)
     Testing DiffEqBase tests passed

**Comment by ChrisRackauckas** [comment]
Those are marked purposefully as `@test_broken` as they are cases where automated upconversion fails and doesn't have an easy way to get fixed. But they are safe because they correctly throw an error (which is what `@test_broken` checks for, if it didn't error and silently gave wrong values then `@test_broken` would not pass), which is the current expected behavior. What it means is that if you hit one of those cases (which are rather obscure) then ForwardDiff differentiation would throw an error that it cannot differentiate the code and it can require one manually upconverts `u0`. All of those cases involve infinitely recursive type definitions though, which is not recommended anyways.
